[package]
name = "mantle-diver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
derivative = "2.2.0"
egui-sfml = "0.4.0"
egui = "0.21.0"
fnv = "1.0.7"
hecs = "0.10.3"
num-traits = "0.2.15"
rand = "0.8.5"
rfd = "0.11.3"
sfml = "0.20.0"
worldgen = "0.5.3"
rmp-serde = "1.1.1"
serde = { version = "1.0.160", features = ["derive"] }
log = "0.4.17"
env_logger = "0.10.0"
zstd = "0.12.3"
clap = { version = "4.2.2", features = ["derive"] }
directories = "5.0.0"
texture_packer = "0.25.0"
walkdir = "2.3.3"
image = "0.24.6"

[dependencies.s2dc]
#git = "https://github.com/crumblingstatue/s2dc.git"
path = "/home/dew/projects/github/s2dc"
features = ["serde"]

[dependencies.sfml-xt]
git = "https://github.com/crumblingstatue/sfml-xt.git"

[dependencies.gamedebug_core]
git = "https://github.com/crumblingstatue/gamedebug_core.git"

[dependencies.egui-inspect]
git = "https://github.com/crumblingstatue/egui-inspect.git"
