[package]
name = "mantle-diver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
egui-sfml = "0.4.0"
fnv = "1.0.7"
hecs = "0.10.1"
rand = "0.8.5"
rfd = "0.11.3"
sfml = "0.20.0"

[dependencies.s2dc]
git = "https://github.com/crumblingstatue/s2dc.git"

[dependencies.sfml-xt]
git = "https://github.com/crumblingstatue/sfml-xt.git"
